export const typingTestTexts = [
    `Success is not final, and failure is not fatal: it is the courage to continue that counts. Every person who has ever achieved something great has faced moments of self-doubt, setbacks, and overwhelming obstacles. But what sets them apart is their refusal to give up when things got tough. You have to believe in yourself even when no one else does, and push forward with discipline, consistency, and passion. There will be days when you feel tired, when nothing goes right, and when the results don’t reflect your effort — those are the days that shape your future. Embrace the grind, trust the process, and stay focused on your goals.`,
  
    `Don't be pushed around by the fears in your mind. Be led by the dreams in your heart, and fuel your actions with intention. The path to success is rarely straight or smooth, but each twist and turn builds resilience. When things don't go as planned, don’t retreat — reassess, adapt, and move forward. Growth doesn’t come from comfort zones; it comes from being challenged and pushing beyond limits. Every little step matters, even the ones that feel invisible. Keep showing up for yourself, even when the progress feels slow.`,
  
    `The only limit to our realization of tomorrow will be our doubts of today. Doubt is natural, but don't let it anchor your potential. You don’t need to have all the answers to begin — just a strong why and the determination to figure things out along the way. Time will pass whether you act or not, so choose action. Invest in your skills, your mindset, and your dreams. You will never regret trying, but you might regret never starting. The version of you you admire is built one decision at a time.`,
  
    `Discipline is the bridge between goals and accomplishments. Talent gets you started, but habits keep you going. You won’t always be motivated, and that’s okay — motivation is fleeting, but discipline is what keeps you consistent when emotions fade. Set routines, stay organized, and don’t let temporary feelings override permanent goals. Real success is built quietly, behind the scenes, in moments where no one is watching. Trust the process, celebrate small wins, and keep grinding until excellence becomes your standard.`,
  
    `If you want something you've never had, you must be willing to do something you've never done. Growth starts where comfort ends. You will never level up by doing what’s easy — you level up by choosing hard things on purpose. Failures will come, and that’s part of it. Don’t fear them. Learn, adjust, and bounce back stronger. Every champion was once a beginner who refused to quit. Time, energy, and consistency — that’s the real magic combo. Keep going, and you’ll be shocked at who you become.`
  ];

